version: "3"

services:
  gotify:
    image: gotify/server-arm7:latest
    container_name: gotify
    ports:
      - 8020:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=admin
      - TZ='Europe/Budapest'
    volumes:
      - gotify_data:/app/data
    restart: unless-stopped

volumes:
  gotify_data:
    driver: local
